### ISSUE TITLE
Code for Self-supervised feature learning

### ISSUE THREAD

**Issue by VedantDave1997** [fredfyyang/Touch-and-Go#2]
Hello @fredfyyang 
Thanks for the code and the dataset. I was wondering if the code is available for Self-supervised representation learning (Section 4.1) and for Material understanding task (Section 5.1). I wanted to use the dataset for my own SSL framework and compare it with yours. Thanks.

**Comment by fredfyyang** [comment]
Sorry for the late reply, we just release the code for this application.

**Comment by vedantdave97** [comment]
Thanks a lot.
