### ISSUE TITLE
Class names for the dataset

### ISSUE THREAD

**Issue by StanLei52** [fredfyyang/Touch-and-Go#3]
Hi @fredfyyang, thank you for releasing the code and dataset. I noticed that for the self-supervised related tasks, the class labels are released. I wonder if it is possible for you to release the class names / class-label mapping for each task. Thanks in advance!

**Comment by fredfyyang** [comment]
Please refer to the category reference in https://drive.google.com/drive/folders/1NDasyshDCL9aaQzxjn_-Q5MBURRT360B
